### PR TITLE
Photo consent

### LINKED ISSUE #231: Photo Consent
We need to record if a band has consented to photography/videography or not.

We also need to keep a log of any changes to this - for example if consent is granted, we take a load of photos, THEN consent is revoked, it is a lot different to taking photos without consent.

If a band has consented, we also need an optional "notes" field for recording details of any members that cannot be photographed even if the rest can.

These fields should be added to the `Organisation` profile page

### PR DESCRIPTION
**Pull request by rugulous**
Closes #231 
Also spotted #270 so this fixes that too

### CODE REVIEW

**Comment by matt-fidd** [comment]
I'm having some problems with this in dev, it looks like I can post the yes...but form with no details given, and then once details are given it's locked and I can't amend the notes anymore. Is this intended behaviour or have I hit a bug?

https://dev.admin.byba.online/organisation/14/

**Comment by matt-fidd** [comment]
Oh, and is there a complimentary Library PR to review please?

**Comment by rugulous** [comment]
@matt-fidd changes should be there now

**Review by matt-fidd — APPROVED** [review]

**Comment by matt-fidd** [comment]
Sorry, conflict resolution time!

**Pull request merged**
